/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marylove.vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class FichaHistoriaClinica extends javax.swing.JFrame {

    /**
     * Creates new form FichaHistoriaClinica
     */
    public FichaHistoriaClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        Tabbed = new javax.swing.JTabbedPane();
        pnlDemanda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        chxTVImplicita = new javax.swing.JCheckBox();
        chxTVExplicita = new javax.swing.JCheckBox();
        txtHistoriaViolencia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelDesarrollo1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txaBiografiaPsicologica1 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        scpValoracion = new javax.swing.JScrollPane();
        PanelValoracion = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtFuncionesMentales = new javax.swing.JTextField();
        txtConducta = new javax.swing.JTextField();
        txtSensoperecepcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAtencion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAfectividad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaAplicacionPruebas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFuncionesCognitivas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        txtEstadoConciencia = new javax.swing.JTextField();
        txtOrientacion = new javax.swing.JTextField();
        scpPlanificacion = new javax.swing.JScrollPane();
        PanelPlanificacion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaFormulacion = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaDiagnosticoInformal = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaDiagnosticoDiferencial = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txaTecnicas = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txaRecomendaciones = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txaCriterios = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtPsicologa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Historia Clinica");

        lbFecha.setText("Fecha: ");

        lbNombre.setText("Nombre: ");

        lbCodigo.setText("Código");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFecha)
                            .addComponent(lbNombre))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addComponent(lbCodigo)
                        .addGap(27, 27, 27)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNombre)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCodigo)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(565, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pnlDemanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Historia de violencia:");

        jLabel1.setText("Demanda:");

        chxTVImplicita.setText("Implícita");

        chxTVExplicita.setText("Explicita");

        jLabel25.setText("Tipo de Violencia:");

        javax.swing.GroupLayout pnlDemandaLayout = new javax.swing.GroupLayout(pnlDemanda);
        pnlDemanda.setLayout(pnlDemandaLayout);
        pnlDemandaLayout.setHorizontalGroup(
            pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDemandaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(pnlDemandaLayout.createSequentialGroup()
                        .addComponent(chxTVImplicita)
                        .addGap(97, 97, 97)
                        .addComponent(chxTVExplicita))
                    .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(pnlDemandaLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtHistoriaViolencia)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnlDemandaLayout.setVerticalGroup(
            pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDemandaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel25)
                .addGap(27, 27, 27)
                .addGroup(pnlDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chxTVImplicita)
                    .addComponent(chxTVExplicita))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(txtHistoriaViolencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        Tabbed.addTab("Cabecera", pnlDemanda);

        PanelDesarrollo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("Biografía Psicologica Personal:");

        txaBiografiaPsicologica1.setColumns(20);
        txaBiografiaPsicologica1.setRows(5);
        jScrollPane12.setViewportView(txaBiografiaPsicologica1);

        jLabel28.setText("Genoframa Familiar: ");

        btnAgregar1.setText("Agregar Genograma");

        jLabel29.setText("img");
        jLabel29.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout PanelDesarrollo1Layout = new javax.swing.GroupLayout(PanelDesarrollo1);
        PanelDesarrollo1.setLayout(PanelDesarrollo1Layout);
        PanelDesarrollo1Layout.setHorizontalGroup(
            PanelDesarrollo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesarrollo1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelDesarrollo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDesarrollo1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(57, 57, 57)
                        .addComponent(btnAgregar1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        PanelDesarrollo1Layout.setVerticalGroup(
            PanelDesarrollo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesarrollo1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelDesarrollo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(btnAgregar1))
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(PanelDesarrollo1);

        Tabbed.addTab("Desarrollo", jScrollPane1);

        jLabel15.setText("Funciones Mentales superiores:");

        jLabel9.setText("Estado de conciencia:");

        jLabel10.setText("Orientación:");

        jLabel7.setText("Conducta: ");

        jLabel8.setText("Funciones cognitivas del sensorio:");

        jLabel14.setText("Afectividad:");

        jLabel5.setText("Aplicación de pruebas psicológicas y resultados: ");

        txaAplicacionPruebas.setColumns(20);
        txaAplicacionPruebas.setRows(5);
        jScrollPane4.setViewportView(txaAplicacionPruebas);

        jLabel6.setText("Valoración del estado psicológico de la persona(Valorar los factores orgánicos /fisiologicos)");

        jLabel13.setText("Sensopercepción:");

        jLabel12.setText("Atención y concentración:");

        jLabel11.setText("Memoria:");

        javax.swing.GroupLayout PanelValoracionLayout = new javax.swing.GroupLayout(PanelValoracion);
        PanelValoracion.setLayout(PanelValoracionLayout);
        PanelValoracionLayout.setHorizontalGroup(
            PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelValoracionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelValoracionLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelValoracionLayout.createSequentialGroup()
                        .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addGroup(PanelValoracionLayout.createSequentialGroup()
                                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFuncionesMentales, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                    .addComponent(txtSensoperecepcion)
                                    .addComponent(txtAtencion)
                                    .addComponent(txtMemoria)
                                    .addComponent(txtOrientacion)
                                    .addComponent(txtEstadoConciencia)
                                    .addComponent(txtAfectividad)
                                    .addComponent(txtFuncionesCognitivas)
                                    .addComponent(txtConducta))))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelValoracionLayout.createSequentialGroup()
                        .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelValoracionLayout.setVerticalGroup(
            PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelValoracionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtConducta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFuncionesCognitivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEstadoConciencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtOrientacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSensoperecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAfectividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtFuncionesMentales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(582, Short.MAX_VALUE))
        );

        scpValoracion.setViewportView(PanelValoracion);

        Tabbed.addTab("Valoración", scpValoracion);

        PanelPlanificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Planificación del proceso");

        jLabel17.setText("Formulación dinámica del problema:");

        txaFormulacion.setColumns(20);
        txaFormulacion.setRows(5);
        jScrollPane5.setViewportView(txaFormulacion);

        jLabel18.setText("Diagnóstico Informal:");

        txaDiagnosticoInformal.setColumns(20);
        txaDiagnosticoInformal.setRows(5);
        jScrollPane6.setViewportView(txaDiagnosticoInformal);

        jLabel19.setText("Diagnostico Diferencial:");

        txaDiagnosticoDiferencial.setColumns(20);
        txaDiagnosticoDiferencial.setRows(5);
        jScrollPane7.setViewportView(txaDiagnosticoDiferencial);

        jLabel20.setText("Descripción de la Personalidad:");

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane8.setViewportView(txaDescripcion);

        jLabel21.setText("Señalamiento de técnicas:");

        txaTecnicas.setColumns(20);
        txaTecnicas.setRows(5);
        jScrollPane9.setViewportView(txaTecnicas);

        jLabel22.setText("Recomendaciones:");

        txaRecomendaciones.setColumns(20);
        txaRecomendaciones.setRows(5);
        jScrollPane10.setViewportView(txaRecomendaciones);

        jLabel23.setText("Criterios Pronósticos:");

        txaCriterios.setColumns(20);
        txaCriterios.setRows(5);
        jScrollPane11.setViewportView(txaCriterios);

        jLabel24.setText("Psicóloga:");

        javax.swing.GroupLayout PanelPlanificacionLayout = new javax.swing.GroupLayout(PanelPlanificacion);
        PanelPlanificacion.setLayout(PanelPlanificacionLayout);
        PanelPlanificacionLayout.setHorizontalGroup(
            PanelPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlanificacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addGroup(PanelPlanificacionLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(41, 41, 41)
                        .addComponent(txtPsicologa, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPlanificacionLayout.setVerticalGroup(
            PanelPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlanificacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(PanelPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtPsicologa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        scpPlanificacion.setViewportView(PanelPlanificacion);

        Tabbed.addTab("Planificación", scpPlanificacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelCabecera() {
        return pnlDemanda;
    }

    public void setPanelCabecera(JPanel PanelCabecera) {
        this.pnlDemanda = PanelCabecera;
    }

    public JPanel getPanelPlanificacion() {
        return PanelPlanificacion;
    }

    public void setPanelPlanificacion(JPanel PanelPlanificacion) {
        this.PanelPlanificacion = PanelPlanificacion;
    }

    public JPanel getPanelValoracion() {
        return PanelValoracion;
    }

    public void setPanelValoracion(JPanel PanelValoracion) {
        this.PanelValoracion = PanelValoracion;
    }

    public JCheckBox getChxTVExplicita() {
        return chxTVExplicita;
    }

    public void setChxTVExplicita(JCheckBox chxTVExplicita) {
        this.chxTVExplicita = chxTVExplicita;
    }

    public JCheckBox getChxTVImplicita() {
        return chxTVImplicita;
    }

    public void setChxTVImplicita(JCheckBox chxTVImplicita) {
        this.chxTVImplicita = chxTVImplicita;
    }

 
    public JTextArea getTxaAplicacionPruebas() {
        return txaAplicacionPruebas;
    }

    public void setTxaAplicacionPruebas(JTextArea txaAplicacionPruebas) {
        this.txaAplicacionPruebas = txaAplicacionPruebas;
    }



    public JTextArea getTxaCriterios() {
        return txaCriterios;
    }

    public void setTxaCriterios(JTextArea txaCriterios) {
        this.txaCriterios = txaCriterios;
    }

    public JTextArea getTxaDescripcion() {
        return txaDescripcion;
    }

    public void setTxaDescripcion(JTextArea txaDescripcion) {
        this.txaDescripcion = txaDescripcion;
    }

    public JTextArea getTxaDiagnosticoDiferencial() {
        return txaDiagnosticoDiferencial;
    }

    public void setTxaDiagnosticoDiferencial(JTextArea txaDiagnosticoDiferencial) {
        this.txaDiagnosticoDiferencial = txaDiagnosticoDiferencial;
    }

    public JTextArea getTxaDiagnosticoInformal() {
        return txaDiagnosticoInformal;
    }

    public void setTxaDiagnosticoInformal(JTextArea txaDiagnosticoInformal) {
        this.txaDiagnosticoInformal = txaDiagnosticoInformal;
    }

    public JTextArea getTxaFormulacion() {
        return txaFormulacion;
    }

    public void setTxaFormulacion(JTextArea txaFormulacion) {
        this.txaFormulacion = txaFormulacion;
    }

    public JTextArea getTxaRecomendaciones() {
        return txaRecomendaciones;
    }

    public void setTxaRecomendaciones(JTextArea txaRecomendaciones) {
        this.txaRecomendaciones = txaRecomendaciones;
    }

    public JTextArea getTxaTecnicas() {
        return txaTecnicas;
    }

    public void setTxaTecnicas(JTextArea txaTecnicas) {
        this.txaTecnicas = txaTecnicas;
    }

    public JTextField getTxtAfectividad() {
        return txtAfectividad;
    }

    public void setTxtAfectividad(JTextField txtAfectividad) {
        this.txtAfectividad = txtAfectividad;
    }

    public JTextField getTxtAtencion() {
        return txtAtencion;
    }

    public void setTxtAtencion(JTextField txtAtencion) {
        this.txtAtencion = txtAtencion;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    public JTextField getTxtConducta() {
        return txtConducta;
    }

    public void setTxtConducta(JTextField txtConducta) {
        this.txtConducta = txtConducta;
    }

    public JTextField getTxtDemanda() {
        return txtDemanda;
    }

    public void setTxtDemanda(JTextField txtDemanda) {
        this.txtDemanda = txtDemanda;
    }

    public JTextField getTxtEstadoConciencia() {
        return txtEstadoConciencia;
    }

    public void setTxtEstadoConciencia(JTextField txtEstadoConciencia) {
        this.txtEstadoConciencia = txtEstadoConciencia;
    }

    public JTextField getTxtFuncionesCognitivas() {
        return txtFuncionesCognitivas;
    }

    public void setTxtFuncionesCognitivas(JTextField txtFuncionesCognitivas) {
        this.txtFuncionesCognitivas = txtFuncionesCognitivas;
    }

    public JTextField getTxtFuncionesMentales() {
        return txtFuncionesMentales;
    }

    public void setTxtFuncionesMentales(JTextField txtFuncionesMentales) {
        this.txtFuncionesMentales = txtFuncionesMentales;
    }

    public JTextField getTxtHistoriaViolencia() {
        return txtHistoriaViolencia;
    }

    public void setTxtHistoriaViolencia(JTextField txtHistoriaViolencia) {
        this.txtHistoriaViolencia = txtHistoriaViolencia;
    }

    public JTextField getTxtMemoria() {
        return txtMemoria;
    }

    public void setTxtMemoria(JTextField txtMemoria) {
        this.txtMemoria = txtMemoria;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtOrientacion() {
        return txtOrientacion;
    }

    public void setTxtOrientacion(JTextField txtOrientacion) {
        this.txtOrientacion = txtOrientacion;
    }

    public JTextField getTxtPsicologa() {
        return txtPsicologa;
    }

    public void setTxtPsicologa(JTextField txtPsicologa) {
        this.txtPsicologa = txtPsicologa;
    }

    public JTextField getTxtSensoperecepcion() {
        return txtSensoperecepcion;
    }

    public void setTxtSensoperecepcion(JTextField txtSensoperecepcion) {
        this.txtSensoperecepcion = txtSensoperecepcion;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaHistoriaClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDesarrollo1;
    private javax.swing.JPanel PanelPlanificacion;
    private javax.swing.JPanel PanelValoracion;
    private javax.swing.JTabbedPane Tabbed;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chxTVExplicita;
    private javax.swing.JCheckBox chxTVImplicita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDemanda;
    private javax.swing.JScrollPane scpPlanificacion;
    private javax.swing.JScrollPane scpValoracion;
    private javax.swing.JTextArea txaAplicacionPruebas;
    private javax.swing.JTextArea txaBiografiaPsicologica1;
    private javax.swing.JTextArea txaCriterios;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextArea txaDiagnosticoDiferencial;
    private javax.swing.JTextArea txaDiagnosticoInformal;
    private javax.swing.JTextArea txaFormulacion;
    private javax.swing.JTextArea txaRecomendaciones;
    private javax.swing.JTextArea txaTecnicas;
    private javax.swing.JTextField txtAfectividad;
    private javax.swing.JTextField txtAtencion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConducta;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JTextField txtEstadoConciencia;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFuncionesCognitivas;
    private javax.swing.JTextField txtFuncionesMentales;
    private javax.swing.JTextField txtHistoriaViolencia;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrientacion;
    private javax.swing.JTextField txtPsicologa;
    private javax.swing.JTextField txtSensoperecepcion;
    // End of variables declaration//GEN-END:variables
}
