/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marylove.vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class vistaCuentasDiarias extends javax.swing.JFrame {

    /**
     * Creates new form vistaCuentasDiarias
     */
    public vistaCuentasDiarias() {
        initComponents();
    }

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }
    

    public JTextArea getTxtaDescrip() {
        return txtaDescrip;
    }

    public void setTxtaDescrip(JTextArea txtaDescrip) {
        this.txtaDescrip = txtaDescrip;
    }

    public JButton getBtnGuardarCuentasDiarias() {
        return btnGuardarCuentasDiarias;
    }

    public void setBtnGuardarCuentasDiarias(JButton btnGuardarCuentasDiarias) {
        this.btnGuardarCuentasDiarias = btnGuardarCuentasDiarias;
    }

    public JDateChooser getDatFechaCuentaDiaria() {
        return datFechaCuentaDiaria;
    }

    public void setDatFechaCuentaDiaria(JDateChooser datFechaCuentaDiaria) {
        this.datFechaCuentaDiaria = datFechaCuentaDiaria;
    }

    public JTextArea getjTextArea1() {
        return txtaDescrip;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.txtaDescrip = jTextArea1;
    }

    public JPanel getPnlCuentasDiarias() {
        return pnlCuentasDiarias;
    }

    public void setPnlCuentasDiarias(JPanel pnlCuentasDiarias) {
        this.pnlCuentasDiarias = pnlCuentasDiarias;
    }

    public JTextField getTxtgastoCuentaDia() {
        return txtgastoCuentaDia;
    }

    public void setTxtgastoCuentaDia(JTextField txtgastoCuentaDia) {
        this.txtgastoCuentaDia = txtgastoCuentaDia;
    }

    public JTextField getTxtsaldoCuentaDia() {
        return txtsaldoCuentaDia;
    }

    public void setTxtsaldoCuentaDia(JTextField txtsaldoCuentaDia) {
        this.txtsaldoCuentaDia = txtsaldoCuentaDia;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCuentasDiarias = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        datFechaCuentaDiaria = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtgastoCuentaDia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsaldoCuentaDia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescrip = new javax.swing.JTextArea();
        btnGuardarCuentasDiarias = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CUENTAS DIARIAS");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Gasto: ");

        jLabel4.setText("Saldo: ");

        jLabel5.setText("Descripción del Gasto:");

        txtaDescrip.setColumns(20);
        txtaDescrip.setRows(5);
        txtaDescrip.setText("\n");
        jScrollPane1.setViewportView(txtaDescrip);

        btnGuardarCuentasDiarias.setText("Guardar");

        btnCancelar.setText("Cancelar");

        btnEditar.setText("Editar");

        lblCodigo.setText("cod");

        javax.swing.GroupLayout pnlCuentasDiariasLayout = new javax.swing.GroupLayout(pnlCuentasDiarias);
        pnlCuentasDiarias.setLayout(pnlCuentasDiariasLayout);
        pnlCuentasDiariasLayout.setHorizontalGroup(
            pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasDiariasLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCuentasDiariasLayout.createSequentialGroup()
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarCuentasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCuentasDiariasLayout.createSequentialGroup()
                        .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlCuentasDiariasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtgastoCuentaDia))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCuentasDiariasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsaldoCuentaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datFechaCuentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        pnlCuentasDiariasLayout.setVerticalGroup(
            pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasDiariasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtgastoCuentaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datFechaCuentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsaldoCuentaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCuentasDiariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCuentasDiarias)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar)
                    .addComponent(lblCodigo))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCuentasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCuentasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCuentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCuentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCuentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCuentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCuentasDiarias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardarCuentasDiarias;
    private com.toedter.calendar.JDateChooser datFechaCuentaDiaria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JPanel pnlCuentasDiarias;
    private javax.swing.JTextArea txtaDescrip;
    private javax.swing.JTextField txtgastoCuentaDia;
    private javax.swing.JTextField txtsaldoCuentaDia;
    // End of variables declaration//GEN-END:variables
}
