/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marylove.vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Angel Lucero
 */
public class VistaPlanAutonomía extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlanAutonomía
     */
    public VistaPlanAutonomía() {
        initComponents();
    }

    public JPanel getPnlPlanAuton() {
        return pnlPlanAuton;
    }

    public void setPnlPlanAuton(JPanel pnlPlanAuton) {
        this.pnlPlanAuton = pnlPlanAuton;
    }

    public JButton getBtnPAcanc() {
        return btnPAcanc;
    }

    public void setBtnPAcanc(JButton btnPAcanc) {
        this.btnPAcanc = btnPAcanc;
    }

    public JButton getBtnPAguard() {
        return btnPAguard;
    }

    public void setBtnPAguard(JButton btnPAguard) {
        this.btnPAguard = btnPAguard;
    }

    public JDateChooser getDtcfechElab() {
        return dtcfechElab;
    }

    public void setDtcfechElab(JDateChooser dtcfechElab) {
        this.dtcfechElab = dtcfechElab;
    }

    public JTextField getTxtPAced() {
        return txtPAced;
    }

    public void setTxtPAced(JTextField txtPAced) {
        this.txtPAced = txtPAced;
    }

    public JTextField getTxtPAcodVic() {
        return txtPAcodVic;
    }

    public void setTxtPAcodVic(JTextField txtPAcodVic) {
        this.txtPAcodVic = txtPAcodVic;
    }

    public JTextField getTxtPAfacries() {
        return txtPAfacries;
    }

    public void setTxtPAfacries(JTextField txtPAfacries) {
        this.txtPAfacries = txtPAfacries;
    }

    public JTextField getTxtPAproeduc() {
        return txtPAproeduc;
    }

    public void setTxtPAproeduc(JTextField txtPAproeduc) {
        this.txtPAproeduc = txtPAproeduc;
    }

    public JTextField getTxtPArecseg() {
        return txtPArecseg;
    }

    public void setTxtPArecseg(JTextField txtPArecseg) {
        this.txtPArecseg = txtPArecseg;
    }

    public JTextField getTxtPAsalud() {
        return txtPAsalud;
    }

    public void setTxtPAsalud(JTextField txtPAsalud) {
        this.txtPAsalud = txtPAsalud;
    }

    public JTextField getTxtautecon() {
        return txtautecon;
    }

    public void setTxtautecon(JTextField txtautecon) {
        this.txtautecon = txtautecon;
    }

    public JTextField getTxtevalproc() {
        return txtevalproc;
    }

    public void setTxtevalproc(JTextField txtevalproc) {
        this.txtevalproc = txtevalproc;
    }

    public JDateChooser getDtcPAfechegre() {
        return dtcPAfechegre;
    }

    public void setDtcPAfechegre(JDateChooser dtcPAfechegre) {
        this.dtcPAfechegre = dtcPAfechegre;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPlanAuton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPAced = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPAcodVic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtcfechElab = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtevalproc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtautecon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPAsalud = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPAproeduc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPArecseg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPAfacries = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dtcPAfechegre = new com.toedter.calendar.JDateChooser();
        btnPAcanc = new javax.swing.JButton();
        btnPAguard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLAN DE AUTONOMIA");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Código:");

        jLabel4.setText("Fecha:");

        jLabel5.setText("Evaluación proceso:");

        jLabel6.setText("Objetos fuera de Casa de Acogida:");

        jLabel7.setText("Para el logro de autonomía económica:");

        jLabel8.setText("Para la estabilidad de la salud física y mental del grupo familiar:");

        jLabel9.setText("Para los sostenimientos de los procesos educativos de los integrantes de la unidad familiar ");

        jLabel10.setText("Para la construcción y sostenimiento de redes seguras:");

        jLabel11.setText("Para la disminución de factores de riesgo:");

        jLabel12.setText("Fecha de egreso:");

        btnPAcanc.setText("Cancelar");

        btnPAguard.setText("Guardar");

        javax.swing.GroupLayout pnlPlanAutonLayout = new javax.swing.GroupLayout(pnlPlanAuton);
        pnlPlanAuton.setLayout(pnlPlanAutonLayout);
        pnlPlanAutonLayout.setHorizontalGroup(
            pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtevalproc, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtautecon)
            .addComponent(txtPAsalud, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtPAproeduc, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtPArecseg)
            .addComponent(txtPAfacries)
            .addGroup(pnlPlanAutonLayout.createSequentialGroup()
                .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(pnlPlanAutonLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addGroup(pnlPlanAutonLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcPAfechegre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlanAutonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPlanAutonLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPAced, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPAcodVic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtcfechElab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlanAutonLayout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(btnPAguard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPAcanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPlanAutonLayout.setVerticalGroup(
            pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanAutonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPAced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtPAcodVic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(dtcfechElab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtevalproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtautecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPAsalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPAproeduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPArecseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPAfacries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(dtcPAfechegre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlPlanAutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPAcanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPAguard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlanAuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlanAuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPAcanc;
    private javax.swing.JButton btnPAguard;
    private com.toedter.calendar.JDateChooser dtcPAfechegre;
    private com.toedter.calendar.JDateChooser dtcfechElab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlPlanAuton;
    private javax.swing.JTextField txtPAced;
    private javax.swing.JTextField txtPAcodVic;
    private javax.swing.JTextField txtPAfacries;
    private javax.swing.JTextField txtPAproeduc;
    private javax.swing.JTextField txtPArecseg;
    private javax.swing.JTextField txtPAsalud;
    private javax.swing.JTextField txtautecon;
    private javax.swing.JTextField txtevalproc;
    // End of variables declaration//GEN-END:variables
}
